env: &env
  environment:
    GO111MODULE: auto
defaults: &defaults
  docker:
    - image: 087285199408.dkr.ecr.us-east-1.amazonaws.com/circle-ci-test-image-base:go1.21.9-tf1.5-tg39.1-pck1.8-ci54.0
  <<: *env
run_precommit: &run_precommit
  # Fail the build if the pre-commit hooks don't pass. Note: if you run $ pre-commit install locally within this repo, these hooks will
  # execute automatically every time before you commit, ensuring the build never fails at this step!
  name: run pre-commit hooks
  command: |
    pre-commit install
    pre-commit run --all-files
version: 2.1
# ---------------------------------------------------------------------------------------------------------------------
# REUSABLE STEPS
# ---------------------------------------------------------------------------------------------------------------------
commands:
  store_results:
    description: Store test results for easy viewing.
    steps:
      - run:
          command: terratest_log_parser --testlog /tmp/logs/all.log --outputdir /tmp/logs
          when: always
      - store_artifacts:
          path: /tmp/logs
      - store_test_results:
          path: /tmp/logs
#----------------------------------------------------------------------------------------------------------------------
# BUILD JOBS
#----------------------------------------------------------------------------------------------------------------------
jobs:
  precommit:
    <<: *defaults
    steps:
      - checkout
      # Fail the build if the pre-commit hooks don't pass. Note: if you run pre-commit install locally, these hooks will
      # execute automatically every time before you commit, ensuring the build never fails at this step!
      - run:
          <<: *run_precommit
  tests:
    <<: *defaults
    docker:
      - image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run: 
          name: Run tests
          command: |
            mkdir -p /tmp/logs
            run-go-tests \
              --path test \
              --timeout 60m \
              --packages . \
              | (tee /tmp/logs/all.log || true)
      - store_results
      - run:
          name: Post upgrade test results
          command: ./.circleci/post-upgrade-test-results.sh
          when: always
#----------------------------------------------------------------------------------------------------------------------
# WORKFLOWS
#----------------------------------------------------------------------------------------------------------------------
workflows:
  version: 2
  build-and-test:
    jobs:
      - precommit:
          context:
            - AWS__PHXDEVOPS__circle-ci-test
            - GITHUB__PAT__gruntwork-ci
          filters:
            tags:
              only: /^v.*/
      - tests:
          context:
            - AWS__PHXDEVOPS__circle-ci-test
            - GITHUB__PAT__gruntwork-ci
            - SLACK__TOKEN__refarch-deployer-test
            - SLACK__WEBHOOK__refarch-deployer-test
            - SLACK__CHANNEL__test-workflow-approvals
          requires:
            - precommit
          filters:
            tags:
              only: /^v.*/
